#! /usr/bin/python3

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "app"))
from jwbroadcasting import VideoCategory

#category = VideoCategory("VideoOnDemand")
category = VideoCategory("VODMinistryTools")

def print_videos(category, indent=0):
	print("%s%s (%s)" % (" " * indent, category.name, category.key))
	for video in category.videos:
		print("%s%s" % (" " * (indent+2), video.name))
	for subcategory in category.subcategories:
		print_videos(subcategory, indent=indent + 4)

print_videos(category)

