#! /usr/bin/env python3

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "app"))

from models import db, Publications
from jwpubs import JWPubs
from jwbroadcasting import VideoCategory

searcher = JWPubs()
pubs = []
for search_terms in (
		("библиотека/журналы/", dict(yearFilter="2018")),
		("библиотека/журналы/", dict(yearFilter="2019")),
		("библиотека/журналы/", dict(yearFilter="2020")),
		("библиотека/журналы/", dict(yearFilter="2021")),
		("библиотека/журналы/", dict(yearFilter="2018")),
		("библиотека/журналы/", dict(yearFilter="2019")),
		("библиотека/журналы/", dict(yearFilter="2020")),
		("библиотека/журналы/", dict(yearFilter="2021")),
		("библиотека/книги/", dict()),
	):
	pubs.extend(searcher.search(*search_terms))

for video in VideoCategory("VODMinistryTools").videos:
	pubs.append(dict(
			name = video.name,
			code = video.code,
			href = video.player_href,
			thumbnail = video.thumbnail
		))

for pub in pubs:
	print("%-4s %-6s %-20s %s" % (pub['code'], pub.get('issue_code'), pub['name'], pub.get('issue')))
	pubobj = Publications.query.filter_by(code=pub['code'], issue_code=pub.get('issue_code')).one_or_none()
	if pubobj is None:
		pubobj = Publications()
		db.session.add(pubobj)
	for name, value in pub.items():
		setattr(pubobj, name, value)
db.session.commit()

