#! /usr/bin/python3
#
# Run JW-Pubs as a web browser with embedded web server
#
# PyWebview documentation
# https://github.com/r0x0r/pywebview

import sys
import webview
from threading import Thread
import logging

from app import app, socketio

logging.basicConfig(
	level=logging.DEBUG,
	format='%(asctime)s %(levelname)s %(name)s %(message)s',
	datefmt='%H:%M:%S'
	)

def server():
	socketio.run(app, host="127.0.0.1", port=5000, log_output=True)
server_thread = Thread(target=server)
server_thread.daemon = True
server_thread.start()

webview.create_window(
	title = "JW-Pubs",
	url = "http://localhost:5000/" + "/".join(sys.argv[1:]),
	width = 1024,
	height = 800,
	)
webview.start(debug=True)
print("Webview has exited.")

print("Shutting down the web server...")
socketio.stop()
server_thread.join()
print("Server has stopt.")

