#! /usr/bin/python3
#
# This script starts an HTTP server for Pub-Tools and then
# creates a browser widget which connects to it.
#
# This mostly works, but no really well. Problems in KH Player include:
# * Some elements have odd sizes. We corrected at least one of these
#   problems by adding additional CSS rules, but some remain.
# * Drag-and-drop of files into the Scene tab does not work.
# * Drag and drop does not work in the patchbay.
#

import sys
import webview
from threading import Thread
from werkzeug.serving import make_server
import logging

from app import create_app

logging.basicConfig(
	level=logging.DEBUG,
	format='%(asctime)s %(levelname)s %(name)s %(message)s',
	datefmt='%H:%M:%S'
	)

print("Starting embedded web server...")
server = make_server("127.0.0.1", port=5000, app=create_app(), threaded=True)
server_thread = Thread(target=lambda: server.serve_forever())
server_thread.daemon = True
server_thread.start()

print("Starting webview...")
webview.create_window(
	title = "Pub-Tools",
	url = "http://localhost:5000/" + "/".join(sys.argv[1:]),
	width = 1200,
	height = 900,
	)
webview.start(debug=False)
print("Webview has exited.")

print("Shutting down the web server...")
server.shutdown()
server_thread.join()
print("Server has stopt.")

