#! /usr/bin/env python3
# obs2zoom

import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "lib"))
import logging

from obs_ws import ObsEventReader
from obs2zoom import ObsToZoomManual, ObsToZoomAuto
from zoom import ZoomControl

# Modules have the logging level set to INFO except when we are debugging
# them. Let the DEBUG messages through here.
logging.basicConfig(
	level=logging.DEBUG,
	format='%(asctime)s %(levelname)s %(message)s',
	datefmt='%Y-%m-%d %H:%M:%S'
	)

with open("/proc/modules") as modules:
	for line in modules:
		if line.startswith("v4l2loopback "):
			break
	else:
		sys.stderr.write("Module v4l2loopback is not loaded.\n")
		sys.exit(1)

obs = ObsEventReader()
zoom = ZoomControl()

if len(sys.argv) > 1 and sys.argv[1] == "--auto":
	obs2zoom = ObsToZoomAuto(obs, zoom)
else:
	obs2zoom = ObsToZoomManual(obs, zoom)

obs2zoom.mainloop()

